import type { ReactNode } from 'react';
import { useRouter } from 'next/router';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import styles from './Layout.module.css';

const Header = dynamic(
  () => {
    return import('../Header/Header');
  },
  { ssr: false }
);

type Props = {
  children: ReactNode;
};

const Layout = ({ children }: Props) => {
  const router = useRouter();
  const isLayoutNeeded = router.pathname !== '/';

  return (
    <div className={styles.container}>
      <Head>
        <title>Gsus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/jesus.png" />
      </Head>

      <Header />

      {/* 首頁不需兩側layout */}
      <main className={isLayoutNeeded ? styles.main : styles.homePageMain}>
        {children}
      </main>

      <footer className={styles.footer}>
        <p>ⓒ {new Date().getFullYear()} All Rights Reserved</p>
      </footer>
    </div>
  );
};

export default Layout;
