import type { ReactNode } from 'react'
import dynamic from 'next/dynamic';
import Head from 'next/head'
import styles from './Layout.module.css'
import { useRouter } from 'next/router';

const Header = dynamic(
  () => {
    return import('../Header/Header');
  },
  { ssr: false }
);

type LayoutProps = {
    children: ReactNode,
};

const Layout = ({ children }: LayoutProps) => {
  const router = useRouter();
  const isLayoutNeeded = router.pathname !== '/';
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Gsus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/jesus.png" />
      </Head>

      <Header/>

      {/* 首頁不需兩側layout */}
      <main className={ isLayoutNeeded ? styles.main : styles.homePageMain }>
        {children}
      </main>

      <footer className={styles.footer}>
        <p>ⓒ {new Date().getFullYear()} All Rights Reserved</p>
      </footer>
    </div>
  )
}

export default Layout;